package com.changtai.sqlModelDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.changtai.sqlModel.CardReplacementModel;
import com.changtai.sqlModel.ConfigModel;
import com.changtai.sqlModel.DBEntityModel;
import com.changtai.sqlModel.DeviceModel;
import com.changtai.sqlModel.LoginInformationModel;
import com.changtai.sqlModel.LoginModel;
import com.changtai.sqlModel.PriceModel;
import com.changtai.sqlModel.PurchaseRecordModel;
import com.changtai.sqlModel.UserModel;

import com.changtai.sqlModelDao.CardReplacementModelDao;
import com.changtai.sqlModelDao.ConfigModelDao;
import com.changtai.sqlModelDao.DBEntityModelDao;
import com.changtai.sqlModelDao.DeviceModelDao;
import com.changtai.sqlModelDao.LoginInformationModelDao;
import com.changtai.sqlModelDao.LoginModelDao;
import com.changtai.sqlModelDao.PriceModelDao;
import com.changtai.sqlModelDao.PurchaseRecordModelDao;
import com.changtai.sqlModelDao.UserModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cardReplacementModelDaoConfig;
    private final DaoConfig configModelDaoConfig;
    private final DaoConfig dBEntityModelDaoConfig;
    private final DaoConfig deviceModelDaoConfig;
    private final DaoConfig loginInformationModelDaoConfig;
    private final DaoConfig loginModelDaoConfig;
    private final DaoConfig priceModelDaoConfig;
    private final DaoConfig purchaseRecordModelDaoConfig;
    private final DaoConfig userModelDaoConfig;

    private final CardReplacementModelDao cardReplacementModelDao;
    private final ConfigModelDao configModelDao;
    private final DBEntityModelDao dBEntityModelDao;
    private final DeviceModelDao deviceModelDao;
    private final LoginInformationModelDao loginInformationModelDao;
    private final LoginModelDao loginModelDao;
    private final PriceModelDao priceModelDao;
    private final PurchaseRecordModelDao purchaseRecordModelDao;
    private final UserModelDao userModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cardReplacementModelDaoConfig = daoConfigMap.get(CardReplacementModelDao.class).clone();
        cardReplacementModelDaoConfig.initIdentityScope(type);

        configModelDaoConfig = daoConfigMap.get(ConfigModelDao.class).clone();
        configModelDaoConfig.initIdentityScope(type);

        dBEntityModelDaoConfig = daoConfigMap.get(DBEntityModelDao.class).clone();
        dBEntityModelDaoConfig.initIdentityScope(type);

        deviceModelDaoConfig = daoConfigMap.get(DeviceModelDao.class).clone();
        deviceModelDaoConfig.initIdentityScope(type);

        loginInformationModelDaoConfig = daoConfigMap.get(LoginInformationModelDao.class).clone();
        loginInformationModelDaoConfig.initIdentityScope(type);

        loginModelDaoConfig = daoConfigMap.get(LoginModelDao.class).clone();
        loginModelDaoConfig.initIdentityScope(type);

        priceModelDaoConfig = daoConfigMap.get(PriceModelDao.class).clone();
        priceModelDaoConfig.initIdentityScope(type);

        purchaseRecordModelDaoConfig = daoConfigMap.get(PurchaseRecordModelDao.class).clone();
        purchaseRecordModelDaoConfig.initIdentityScope(type);

        userModelDaoConfig = daoConfigMap.get(UserModelDao.class).clone();
        userModelDaoConfig.initIdentityScope(type);

        cardReplacementModelDao = new CardReplacementModelDao(cardReplacementModelDaoConfig, this);
        configModelDao = new ConfigModelDao(configModelDaoConfig, this);
        dBEntityModelDao = new DBEntityModelDao(dBEntityModelDaoConfig, this);
        deviceModelDao = new DeviceModelDao(deviceModelDaoConfig, this);
        loginInformationModelDao = new LoginInformationModelDao(loginInformationModelDaoConfig, this);
        loginModelDao = new LoginModelDao(loginModelDaoConfig, this);
        priceModelDao = new PriceModelDao(priceModelDaoConfig, this);
        purchaseRecordModelDao = new PurchaseRecordModelDao(purchaseRecordModelDaoConfig, this);
        userModelDao = new UserModelDao(userModelDaoConfig, this);

        registerDao(CardReplacementModel.class, cardReplacementModelDao);
        registerDao(ConfigModel.class, configModelDao);
        registerDao(DBEntityModel.class, dBEntityModelDao);
        registerDao(DeviceModel.class, deviceModelDao);
        registerDao(LoginInformationModel.class, loginInformationModelDao);
        registerDao(LoginModel.class, loginModelDao);
        registerDao(PriceModel.class, priceModelDao);
        registerDao(PurchaseRecordModel.class, purchaseRecordModelDao);
        registerDao(UserModel.class, userModelDao);
    }
    
    public void clear() {
        cardReplacementModelDaoConfig.clearIdentityScope();
        configModelDaoConfig.clearIdentityScope();
        dBEntityModelDaoConfig.clearIdentityScope();
        deviceModelDaoConfig.clearIdentityScope();
        loginInformationModelDaoConfig.clearIdentityScope();
        loginModelDaoConfig.clearIdentityScope();
        priceModelDaoConfig.clearIdentityScope();
        purchaseRecordModelDaoConfig.clearIdentityScope();
        userModelDaoConfig.clearIdentityScope();
    }

    public CardReplacementModelDao getCardReplacementModelDao() {
        return cardReplacementModelDao;
    }

    public ConfigModelDao getConfigModelDao() {
        return configModelDao;
    }

    public DBEntityModelDao getDBEntityModelDao() {
        return dBEntityModelDao;
    }

    public DeviceModelDao getDeviceModelDao() {
        return deviceModelDao;
    }

    public LoginInformationModelDao getLoginInformationModelDao() {
        return loginInformationModelDao;
    }

    public LoginModelDao getLoginModelDao() {
        return loginModelDao;
    }

    public PriceModelDao getPriceModelDao() {
        return priceModelDao;
    }

    public PurchaseRecordModelDao getPurchaseRecordModelDao() {
        return purchaseRecordModelDao;
    }

    public UserModelDao getUserModelDao() {
        return userModelDao;
    }

}
