package com.changtai.sqlModelDao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.changtai.sqlModel.DeviceModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DEVICE_MODEL".
*/
public class DeviceModelDao extends AbstractDao<DeviceModel, Long> {

    public static final String TABLENAME = "DEVICE_MODEL";

    /**
     * Properties of entity DeviceModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property DeviceId = new Property(0, Long.class, "DeviceId", true, "_id");
        public final static Property DeviceNo = new Property(1, String.class, "DeviceNo", false, "DEVICE_NO");
        public final static Property BureauNo = new Property(2, String.class, "BureauNo", false, "BUREAU_NO");
        public final static Property StationNo = new Property(3, String.class, "StationNo", false, "STATION_NO");
        public final static Property GprsNo = new Property(4, String.class, "GprsNo", false, "GPRS_NO");
        public final static Property DeviceName = new Property(5, String.class, "DeviceName", false, "DEVICE_NAME");
        public final static Property Index = new Property(6, int.class, "Index", false, "INDEX");
        public final static Property Linkman = new Property(7, String.class, "Linkman", false, "LINKMAN");
        public final static Property Phone = new Property(8, String.class, "Phone", false, "PHONE");
        public final static Property Location = new Property(9, String.class, "Location", false, "LOCATION");
        public final static Property CreateDatetime = new Property(10, java.util.Date.class, "CreateDatetime", false, "CREATE_DATETIME");
        public final static Property Longitude = new Property(11, String.class, "Longitude", false, "LONGITUDE");
        public final static Property Latitude = new Property(12, String.class, "Latitude", false, "LATITUDE");
        public final static Property Comment = new Property(13, String.class, "Comment", false, "COMMENT");
        public final static Property AdministratorName = new Property(14, String.class, "AdministratorName", false, "ADMINISTRATOR_NAME");
        public final static Property StopFlag = new Property(15, boolean.class, "StopFlag", false, "STOP_FLAG");
        public final static Property ServerVersion = new Property(16, long.class, "ServerVersion", false, "SERVER_VERSION");
        public final static Property ClientVersion = new Property(17, long.class, "ClientVersion", false, "CLIENT_VERSION");
        public final static Property DelFlag = new Property(18, boolean.class, "DelFlag", false, "DEL_FLAG");
        public final static Property Key = new Property(19, int.class, "key", false, "KEY");
    }


    public DeviceModelDao(DaoConfig config) {
        super(config);
    }
    
    public DeviceModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DEVICE_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: DeviceId
                "\"DEVICE_NO\" TEXT," + // 1: DeviceNo
                "\"BUREAU_NO\" TEXT," + // 2: BureauNo
                "\"STATION_NO\" TEXT," + // 3: StationNo
                "\"GPRS_NO\" TEXT," + // 4: GprsNo
                "\"DEVICE_NAME\" TEXT," + // 5: DeviceName
                "\"INDEX\" INTEGER NOT NULL ," + // 6: Index
                "\"LINKMAN\" TEXT," + // 7: Linkman
                "\"PHONE\" TEXT," + // 8: Phone
                "\"LOCATION\" TEXT," + // 9: Location
                "\"CREATE_DATETIME\" INTEGER," + // 10: CreateDatetime
                "\"LONGITUDE\" TEXT," + // 11: Longitude
                "\"LATITUDE\" TEXT," + // 12: Latitude
                "\"COMMENT\" TEXT," + // 13: Comment
                "\"ADMINISTRATOR_NAME\" TEXT," + // 14: AdministratorName
                "\"STOP_FLAG\" INTEGER NOT NULL ," + // 15: StopFlag
                "\"SERVER_VERSION\" INTEGER NOT NULL ," + // 16: ServerVersion
                "\"CLIENT_VERSION\" INTEGER NOT NULL ," + // 17: ClientVersion
                "\"DEL_FLAG\" INTEGER NOT NULL ," + // 18: DelFlag
                "\"KEY\" INTEGER NOT NULL );"); // 19: key
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DEVICE_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DeviceModel entity) {
        stmt.clearBindings();
 
        Long DeviceId = entity.getDeviceId();
        if (DeviceId != null) {
            stmt.bindLong(1, DeviceId);
        }
 
        String DeviceNo = entity.getDeviceNo();
        if (DeviceNo != null) {
            stmt.bindString(2, DeviceNo);
        }
 
        String BureauNo = entity.getBureauNo();
        if (BureauNo != null) {
            stmt.bindString(3, BureauNo);
        }
 
        String StationNo = entity.getStationNo();
        if (StationNo != null) {
            stmt.bindString(4, StationNo);
        }
 
        String GprsNo = entity.getGprsNo();
        if (GprsNo != null) {
            stmt.bindString(5, GprsNo);
        }
 
        String DeviceName = entity.getDeviceName();
        if (DeviceName != null) {
            stmt.bindString(6, DeviceName);
        }
        stmt.bindLong(7, entity.getIndex());
 
        String Linkman = entity.getLinkman();
        if (Linkman != null) {
            stmt.bindString(8, Linkman);
        }
 
        String Phone = entity.getPhone();
        if (Phone != null) {
            stmt.bindString(9, Phone);
        }
 
        String Location = entity.getLocation();
        if (Location != null) {
            stmt.bindString(10, Location);
        }
 
        java.util.Date CreateDatetime = entity.getCreateDatetime();
        if (CreateDatetime != null) {
            stmt.bindLong(11, CreateDatetime.getTime());
        }
 
        String Longitude = entity.getLongitude();
        if (Longitude != null) {
            stmt.bindString(12, Longitude);
        }
 
        String Latitude = entity.getLatitude();
        if (Latitude != null) {
            stmt.bindString(13, Latitude);
        }
 
        String Comment = entity.getComment();
        if (Comment != null) {
            stmt.bindString(14, Comment);
        }
 
        String AdministratorName = entity.getAdministratorName();
        if (AdministratorName != null) {
            stmt.bindString(15, AdministratorName);
        }
        stmt.bindLong(16, entity.getStopFlag() ? 1L: 0L);
        stmt.bindLong(17, entity.getServerVersion());
        stmt.bindLong(18, entity.getClientVersion());
        stmt.bindLong(19, entity.getDelFlag() ? 1L: 0L);
        stmt.bindLong(20, entity.getKey());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DeviceModel entity) {
        stmt.clearBindings();
 
        Long DeviceId = entity.getDeviceId();
        if (DeviceId != null) {
            stmt.bindLong(1, DeviceId);
        }
 
        String DeviceNo = entity.getDeviceNo();
        if (DeviceNo != null) {
            stmt.bindString(2, DeviceNo);
        }
 
        String BureauNo = entity.getBureauNo();
        if (BureauNo != null) {
            stmt.bindString(3, BureauNo);
        }
 
        String StationNo = entity.getStationNo();
        if (StationNo != null) {
            stmt.bindString(4, StationNo);
        }
 
        String GprsNo = entity.getGprsNo();
        if (GprsNo != null) {
            stmt.bindString(5, GprsNo);
        }
 
        String DeviceName = entity.getDeviceName();
        if (DeviceName != null) {
            stmt.bindString(6, DeviceName);
        }
        stmt.bindLong(7, entity.getIndex());
 
        String Linkman = entity.getLinkman();
        if (Linkman != null) {
            stmt.bindString(8, Linkman);
        }
 
        String Phone = entity.getPhone();
        if (Phone != null) {
            stmt.bindString(9, Phone);
        }
 
        String Location = entity.getLocation();
        if (Location != null) {
            stmt.bindString(10, Location);
        }
 
        java.util.Date CreateDatetime = entity.getCreateDatetime();
        if (CreateDatetime != null) {
            stmt.bindLong(11, CreateDatetime.getTime());
        }
 
        String Longitude = entity.getLongitude();
        if (Longitude != null) {
            stmt.bindString(12, Longitude);
        }
 
        String Latitude = entity.getLatitude();
        if (Latitude != null) {
            stmt.bindString(13, Latitude);
        }
 
        String Comment = entity.getComment();
        if (Comment != null) {
            stmt.bindString(14, Comment);
        }
 
        String AdministratorName = entity.getAdministratorName();
        if (AdministratorName != null) {
            stmt.bindString(15, AdministratorName);
        }
        stmt.bindLong(16, entity.getStopFlag() ? 1L: 0L);
        stmt.bindLong(17, entity.getServerVersion());
        stmt.bindLong(18, entity.getClientVersion());
        stmt.bindLong(19, entity.getDelFlag() ? 1L: 0L);
        stmt.bindLong(20, entity.getKey());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DeviceModel readEntity(Cursor cursor, int offset) {
        DeviceModel entity = new DeviceModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // DeviceId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // DeviceNo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // BureauNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // StationNo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // GprsNo
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // DeviceName
            cursor.getInt(offset + 6), // Index
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Linkman
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // Phone
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // Location
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // CreateDatetime
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // Longitude
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // Latitude
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // Comment
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // AdministratorName
            cursor.getShort(offset + 15) != 0, // StopFlag
            cursor.getLong(offset + 16), // ServerVersion
            cursor.getLong(offset + 17), // ClientVersion
            cursor.getShort(offset + 18) != 0, // DelFlag
            cursor.getInt(offset + 19) // key
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DeviceModel entity, int offset) {
        entity.setDeviceId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDeviceNo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBureauNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setStationNo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGprsNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDeviceName(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setIndex(cursor.getInt(offset + 6));
        entity.setLinkman(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setPhone(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setLocation(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCreateDatetime(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setLongitude(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setLatitude(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setComment(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setAdministratorName(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setStopFlag(cursor.getShort(offset + 15) != 0);
        entity.setServerVersion(cursor.getLong(offset + 16));
        entity.setClientVersion(cursor.getLong(offset + 17));
        entity.setDelFlag(cursor.getShort(offset + 18) != 0);
        entity.setKey(cursor.getInt(offset + 19));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DeviceModel entity, long rowId) {
        entity.setDeviceId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DeviceModel entity) {
        if(entity != null) {
            return entity.getDeviceId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DeviceModel entity) {
        return entity.getDeviceId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
